#!/bin/bash
# Builds the Peril image.

cd "$(dirname "$0")"

# Stage 1: unlit markdown sources into executable, but not self-replicating,
#          perl code.
{
  ./unlit image/bootstrap.p.md
  echo 'bootstrap;'
  echo __DATA__
  tar -c peril.p.md image.p.md image
} > peril.boot

# Stage 2: invoke the boot script on itself to build the image.
perl peril.boot --internal/build-image peril.p.md > peril
chmod 755 peril

# Stage 3: ask peril for its own image to make sure it lines up.
if ! (($(wc -c < peril))); then
  echo "FAIL: compiled image is empty" >&2
  exit 1
fi

if [[ $(sha256sum < peril) != $(./peril --internal/image | sha256sum) ]]; then
  echo "FAIL: peril image is not self-replicating" >&2
  exit 1
fi

if ! tar -tf peril > /dev/null; then
  echo "FAIL: peril image cannot be extracted using tar" >&2
  exit 1
fi
