#!/bin/bash
# Builds the Peril image.

cd "$(dirname "$0")"

# Stage 1: unlit markdown sources into executable, but not self-replicating,
#          perl code.
./unlit peril.p.md > peril.boot

# Stage 2: invoke the boot script on itself to build the image.
perl peril.boot --internal/build-image peril.p.md > peril
chmod 755 peril

# Stage 3: ask peril for its own image to make sure it lines up.
if ! (($(wc -c < peril))); then
  echo "FAIL: compiled image is empty" >&2
  exit 1
fi

if [[ $(sha256sum < peril) != $(./peril --internal/image | sha256sum) ]]; then
  echo "FAIL: peril image is not self-replicating" >&2
  exit 1
fi
