#!/usr/bin/env perl
use strict;
use warnings;

sub literate_elements_markdown($$)
{ my ($file, @lines) = ($_[0], '', split /\n/, $_[1]);
  my @toggles        = (0, grep $lines[$_] =~ /^\s*\`\`\`/, 1..$#lines);
  (map((join("\n", @lines[$toggles[$_-2]..$toggles[$_-1]]) =~ /\]\(([^)]+\.md)\)/g,
        [$toggles[$_-1] + 1,
         $lines[$toggles[$_-1]] =~ /^\s*\`\`\`(.*)$/,
         join "\n", @lines[$toggles[$_-1]+1..$toggles[$_]-1]]),
       grep !($_ & 1), 2..$#toggles),
   join("\n", @lines[$toggles[-1]..$#lines]) =~ /\]\(([^)]+\.md)\)/g) }

sub parse($);
sub parse($)
{ my ($f) = @_;
  open my $fh, "< $f" or die "open <$f: $!";
  map ref() ? $$_[1] =~ /^pl|^perl/ ? "#line $$_[0] \"$f\"\n$$_[2]\n" : ()
            : parse $f =~ s|[^/]*$||r . $_,
      literate_elements_markdown $f => join '', <$fh> }

print for map parse($_), @ARGV;
