#!/usr/bin/env perl
use strict;
use warnings;

sub literate_elements_markdown($$)
{ my $file    = shift;
  my @lines   = ("", @_);
  my @toggles = (0, grep $lines[$_] =~ /^\s*\`\`\`/, 1..$#lines);
  (map((join("\n", @lines[$toggles[$_-2]..$toggles[$_-1]]) =~ /\]\(([^)]+\.md)\)/g,
        [$toggles[$_-1] + 1,
         $lines[$toggles[$_-1]] =~ /^\s*\`\`\`(.*)$/,
         join "\n", @lines[$toggles[$_-1]+1..$toggles[$_]-1]]),
       grep !($_ & 1), 1..$#toggles),
   join "\n", @lines[$toggles[-1]..$#lines]) =~ /\]\(([^)]+\.md)\)/g }

sub parse($);
sub parse($)
{ open my $fh, "< $_[0]" or die "open <$_[0] failed: $!";
  map ref() ? $$_[1] =~ /^pl|^perl/ ? "#line $$_[0] \"$_[0]\"\n$$_[2]\n" : ()
            : parse $_[0] =~ s|[^/]*$||r . $_,
      literate_elements_markdown $_[0] => <$fh> }

print for map parse($_), @ARGV;
